In [1]:
import numpy as np
import pandas as pd

In [5]:
index_val = [('cse',2019), ('cse',2020), ('cse',2021), ('cse',2022), ('ece',2019), ('ece',2020), ('ece',2021), ('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8], index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

#### how to create multiindex object

In [11]:
# 1. pd.MultiIndex.from_tuples()

index_val = [('cse',2019), ('cse',2020), ('cse',2021), ('cse',2022), ('ece',2019), ('ece',2020), ('ece',2021), ('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [10]:
multiindex.levels

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [12]:
#  2. pd.MultiIndex.from_product()

pd.MultiIndex.from_product([['cse','ece'],[2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

#### crating a series with multiindex object

In [28]:
# creating a series with multiindex object

s = pd.Series([1,2,3,4,5,6,7,8], index=multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [22]:
#  how to fetch item from such series

# s.loc['cse',2022]
s[('cse', 2022)]

np.int64(4)

In [23]:
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

### unstack

In [32]:
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

### stack

In [34]:
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

### multiindex dataframe

In [37]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index= multiindex,
    columns = ['avg_package','students']
)

branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [38]:
branch_df1.loc['cse']

      avg_package  students
2019            1         2
2020            3         4
2021            5         6
2022            7         8

In [40]:
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package', 'students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [55]:
branch_df2['delhi']['avg_package']
branch_df2.loc[2019]['delhi']['students']
branch_df2.loc[2019, ('delhi','students')]

np.int64(2)

In [43]:
branch_df2.loc[2019]

delhi   avg_package    1
        students       2
mumbai  avg_package    0
        students       0
Name: 2019, dtype: int64

In [45]:
# Multiindex df in terms of both cols and index

branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index= multiindex,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'], ['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [54]:
branch_df3.loc[('cse',2019),('delhi','avg_package')]

np.int64(1)

### Stacking and Unstacking

In [91]:
branch_df1.unstack()

    avg_package                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           1    3    5    7        2    4    6    8
ece           9   11   13   15       10   12   14   16

In [60]:
branch_df1.unstack().unstack()

avg_package  2019  cse     1
                   ece     9
             2020  cse     3
                   ece    11
             2021  cse     5
                   ece    13
             2022  cse     7
                   ece    15
students     2019  cse     2
                   ece    10
             2020  cse     4
                   ece    12
             2021  cse     6
                   ece    14
             2022  cse     8
                   ece    16
dtype: int64

In [95]:
branch_df1.stack(future_stack=True)

cse  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
ece  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

In [100]:
branch_df1.unstack().stack(future_stack=True)

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [101]:
branch_df1.unstack().stack(future_stack=True).stack()

cse  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
ece  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

In [106]:
branch_df2.unstack()

delhi   avg_package  2019    1
                     2020    3
                     2021    5
                     2022    7
        students     2019    2
                     2020    4
                     2021    6
                     2022    8
mumbai  avg_package  2019    0
                     2020    0
                     2021    0
                     2022    0
        students     2019    0
                     2020    0
                     2021    0
                     2022    0
dtype: int64

In [107]:
branch_df2.unstack().unstack()

                    2019  2020  2021  2022
delhi  avg_package     1     3     5     7
       students        2     4     6     8
mumbai avg_package     0     0     0     0
       students        0     0     0     0

In [108]:
branch_df2.unstack().unstack().unstack()

              2019                 2020                 2021           \
       avg_package students avg_package students avg_package students
delhi            1        2           3        4           5        6
mumbai           0        0           0        0           0        0

              2022
       avg_package students
delhi            7        8
mumbai           0        0

In [119]:
branch_df2.stack(future_stack=True)

                  delhi  mumbai
2019 avg_package      1       0
     students         2       0
2020 avg_package      3       0
     students         4       0
2021 avg_package      5       0
     students         6       0
2022 avg_package      7       0
     students         8       0

In [120]:
branch_df2.stack(future_stack=True).stack()

2019  avg_package  delhi     1
                   mumbai    0
      students     delhi     2
                   mumbai    0
2020  avg_package  delhi     3
                   mumbai    0
      students     delhi     4
                   mumbai    0
2021  avg_package  delhi     5
                   mumbai    0
      students     delhi     6
                   mumbai    0
2022  avg_package  delhi     7
                   mumbai    0
      students     delhi     8
                   mumbai    0
dtype: int64

In [111]:
branch_df3.unstack()

          delhi                                             mumbai            \
    avg_package                students                avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           1    3    5    7        2    4    6    8           0    0    0
ece           9   11   13   15       10   12   14   16           0    0    0


         students
    2022     2019 2020 2021 2022
cse    0        0    0    0    0
ece    0        0    0    0    0

In [112]:
branch_df3.unstack().unstack()

delhi   avg_package  2019  cse     1
                           ece     9
                     2020  cse     3
                           ece    11
                     2021  cse     5
                           ece    13
                     2022  cse     7
                           ece    15
        students     2019  cse     2
                           ece    10
                     2020  cse     4
                           ece    12
                     2021  cse     6
                           ece    14
                     2022  cse     8
                           ece    16
mumbai  avg_package  2019  cse     0
                           ece     0
                     2020  cse     0
                           ece     0
                     2021  cse     0
                           ece     0
                     2022  cse     0
                           ece     0
        students     2019  cse     0
                           ece     0
                     2020  cse     0
                           ece     0
                     2021  cse     0
                           ece     0
                     2022  cse     0
                           ece     0
dtype: int64

In [113]:
branch_df3.unstack().unstack().unstack()

                         cse  ece
delhi  avg_package 2019    1    9
                   2020    3   11
                   2021    5   13
                   2022    7   15
       students    2019    2   10
                   2020    4   12
                   2021    6   14
                   2022    8   16
mumbai avg_package 2019    0    0
                   2020    0    0
                   2021    0    0
                   2022    0    0
       students    2019    0    0
                   2020    0    0
                   2021    0    0
                   2022    0    0

In [115]:
branch_df3.stack(future_stack=True)

                      delhi  mumbai
cse 2019 avg_package      1       0
         students         2       0
    2020 avg_package      3       0
         students         4       0
    2021 avg_package      5       0
         students         6       0
    2022 avg_package      7       0
         students         8       0
ece 2019 avg_package      9       0
         students        10       0
    2020 avg_package     11       0
         students        12       0
    2021 avg_package     13       0
         students        14       0
    2022 avg_package     15       0
         students        16       0

In [116]:
branch_df3.stack(future_stack=True).stack()

cse  2019  avg_package  delhi      1
                        mumbai     0
           students     delhi      2
                        mumbai     0
     2020  avg_package  delhi      3
                        mumbai     0
           students     delhi      4
                        mumbai     0
     2021  avg_package  delhi      5
                        mumbai     0
           students     delhi      6
                        mumbai     0
     2022  avg_package  delhi      7
                        mumbai     0
           students     delhi      8
                        mumbai     0
ece  2019  avg_package  delhi      9
                        mumbai     0
           students     delhi     10
                        mumbai     0
     2020  avg_package  delhi     11
                        mumbai     0
           students     delhi     12
                        mumbai     0
     2021  avg_package  delhi     13
                        mumbai     0
           students     delhi     14
                        mumbai     0
     2022  avg_package  delhi     15
                        mumbai     0
           students     delhi     16
                        mumbai     0
dtype: int64

### Working with multiindex dataframes

#### head and tail

In [123]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [126]:
branch_df3.head()

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0

#### shape

In [129]:
branch_df3.shape

(8, 4)

#### info

In [132]:
branch_df3.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, students)      8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 932.0+ bytes

In [134]:
branch_df3.unstack().info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, cse to ece
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   (delhi, avg_package, 2019)   2 non-null      int64
 1   (delhi, avg_package, 2020)   2 non-null      int64
 2   (delhi, avg_package, 2021)   2 non-null      int64
 3   (delhi, avg_package, 2022)   2 non-null      int64
 4   (delhi, students, 2019)      2 non-null      int64
 5   (delhi, students, 2020)      2 non-null      int64
 6   (delhi, students, 2021)      2 non-null      int64
 7   (delhi, students, 2022)      2 non-null      int64
 8   (mumbai, avg_package, 2019)  2 non-null      int64
 9   (mumbai, avg_package, 2020)  2 non-null      int64
 10  (mumbai, avg_package, 2021)  2 non-null      int64
 11  (mumbai, avg_package, 2022)  2 non-null      int64
 12  (mumbai, students, 2019)     2 non-null      int64
 13  (mumbai, students, 2020)     2 non-null      int64
 14  (mumbai, students, 2021)     2 non-null      int64
 15  (mumbai, students, 2022)     2 non-null      int64
dtypes: int64(16)
memory usage: 272.0+ bytes

#### duplicated -> isnull

In [136]:
branch_df3.duplicated()

cse  2019    False
     2020    False
     2021    False
     2022    False
ece  2019    False
     2020    False
     2021    False
     2022    False
dtype: bool

In [138]:
branch_df3.isnull()

               delhi               mumbai
         avg_package students avg_package students
cse 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False
ece 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False

### Extracting rows

#### single

In [140]:
branch_df3.loc[('cse',2022)]

delhi   avg_package    7
        students       8
mumbai  avg_package    0
        students       0
Name: (cse, 2022), dtype: int64

#### multiple

In [144]:
branch_df3.loc[('cse',2019):('ece',2019):2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

### Extracting cols

In [147]:
branch_df3['delhi']['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ece  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [154]:
branch_df3.loc[:,[('delhi','students'),('mumbai','avg_package')]]

            delhi      mumbai
         students avg_package
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ece 2019       10           0
    2020       12           0
    2021       14           0
    2022       16           0

In [157]:
branch_df3.iloc[:,[1,2]]

            delhi      mumbai
         students avg_package
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ece 2019       10           0
    2020       12           0
    2021       14           0
    2022       16           0

#### Extracting both

In [158]:
branch_df3.loc[[('cse',2019),('ece',2019)],[('delhi','students'),('mumbai','avg_package')]]

            delhi      mumbai
         students avg_package
cse 2019        2           0
ece 2019       10           0

In [156]:
branch_df3.iloc[[0,4],[1,2]]

            delhi      mumbai
         students avg_package
cse 2019        2           0
ece 2019       10           0

#### sort index

In [160]:
branch_df3.sort_index(ascending=False)

               delhi               mumbai
         avg_package students avg_package students
ece 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [161]:
branch_df3.sort_index(ascending=[False,True])

               delhi               mumbai
         avg_package students avg_package students
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0

#### Transpose

In [162]:
branch_df3.transpose()

                    cse                 ece
                   2019 2020 2021 2022 2019 2020 2021 2022
delhi  avg_package    1    3    5    7    9   11   13   15
       students       2    4    6    8   10   12   14   16
mumbai avg_package    0    0    0    0    0    0    0    0
       students       0    0    0    0    0    0    0    0

#### swaplevel

In [164]:
branch_df3.swaplevel()

               delhi               mumbai
         avg_package students avg_package students
2019 cse           1        2           0        0
2020 cse           3        4           0        0
2021 cse           5        6           0        0
2022 cse           7        8           0        0
2019 ece           9       10           0        0
2020 ece          11       12           0        0
2021 ece          13       14           0        0
2022 ece          15       16           0        0

In [165]:
branch_df3.swaplevel(axis=1)

         avg_package students avg_package students
               delhi    delhi      mumbai   mumbai
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

### Long Vs Wide Data

wide format is where we have a single row for every data point with multiple cloumns to hold the values of various attributes.

Long format is where, for each data point we have as many rows as the number of attributes and each row contains the value of a particular attributes for a given data point.

#### melt

In [168]:
# wide to long

a = pd.DataFrame({'cse':[120]})
a

   cse
0  120

In [170]:
a.melt()

  variable  value
0      cse    120

In [178]:
df = pd.DataFrame({'cse':[120],'ece':[100],'mech':[50]})
df

   cse  ece  mech
0  120  100    50

In [175]:
df.melt().rename(columns={'variable':'branch','value':'num_students'})

  branch  num_students
0    cse           120
1    ece           100
2   mech            50

In [179]:
temp_df = pd.DataFrame(
    {
        'branch':['cse','ece','mech'],
        '2020': [100,150,60],
        '2021':[120,130,80],
        '2022':[150,140,70]
    }
)

temp_df

  branch  2020  2021  2022
0    cse   100   120   150
1    ece   150   130   140
2   mech    60    80    70

In [183]:
temp_df.melt(id_vars=['branch'], var_name='year', value_name='students')

  branch  year  students
0    cse  2020       100
1    ece  2020       150
2   mech  2020        60
3    cse  2021       120
4    ece  2021       130
5   mech  2021        80
6    cse  2022       150
7    ece  2022       140
8   mech  2022        70

In [185]:
death = pd.read_csv('time_series_covid19_deaths_global.csv')
confirm = pd.read_csv('time_series_covid19_confirmed_global.csv')

In [188]:
death.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,7845,7846,7846,7846,7846,7847,7847,7849,7849,7849
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,3595,3595,3595,3595,3595,3595,3595,3595,3595,3595
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,6881,6881,6881,6881,6881,6881,6881,6881,6881,6881
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,165,165,165,165,165,165,165,165,165,165
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,1928,1928,1928,1930,1930,1930,1930,1930,1930,1930

In [189]:
confirm.head()

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,12/24/22,12/25/22,12/26/22,12/27/22,12/28/22,12/29/22,12/30/22,12/31/22,1/1/23,1/2/23
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,...,207310,207399,207438,207460,207493,207511,207550,207559,207616,207627
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,...,333749,333749,333751,333751,333776,333776,333806,333806,333811,333812
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,...,271194,271198,271198,271202,271208,271217,271223,271228,271229,271229
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,...,47686,47686,47686,47686,47751,47751,47751,47751,47751,47751
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,...,104973,104973,104973,105095,105095,105095,105095,105095,105095,105095

In [197]:
death = death.melt(id_vars=['Province/State', 'Country/Region','Lat','Long'], var_name='date',value_name ='num_deaths')
confirm = confirm.melt(id_vars=['Province/State', 'Country/Region','Lat','Long'], var_name='date',value_name ='num_cases')

In [198]:
death.head()

  Province/State Country/Region       Lat       Long     date  num_deaths
0            NaN    Afghanistan  33.93911  67.709953  1/22/20           0
1            NaN        Albania  41.15330  20.168300  1/22/20           0
2            NaN        Algeria  28.03390   1.659600  1/22/20           0
3            NaN        Andorra  42.50630   1.521800  1/22/20           0
4            NaN         Angola -11.20270  17.873900  1/22/20           0

In [199]:
confirm.head()

  Province/State Country/Region       Lat       Long     date  num_cases
0            NaN    Afghanistan  33.93911  67.709953  1/22/20          0
1            NaN        Albania  41.15330  20.168300  1/22/20          0
2            NaN        Algeria  28.03390   1.659600  1/22/20          0
3            NaN        Andorra  42.50630   1.521800  1/22/20          0
4            NaN         Angola -11.20270  17.873900  1/22/20          0

In [201]:
confirm.merge(death, on = ['Province/State', 'Country/Region','Lat','Long','date'])[['Country/Region','date','num_cases','num_deaths']]

              Country/Region     date  num_cases  num_deaths
0                Afghanistan  1/22/20          0           0
1                    Albania  1/22/20          0           0
2                    Algeria  1/22/20          0           0
3                    Andorra  1/22/20          0           0
4                     Angola  1/22/20          0           0
...                      ...      ...        ...         ...
311248    West Bank and Gaza   1/2/23     703228        5708
311249  Winter Olympics 2022   1/2/23        535           0
311250                 Yemen   1/2/23      11945        2159
311251                Zambia   1/2/23     334661        4024
311252              Zimbabwe   1/2/23     259981        5637

[311253 rows x 4 columns]